export const INACTIVE_ACCOUNT = 'INACTIVE_ACCOUNT';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const OTP_NOT_VALID = 'OTP_NOT_VALID';
export const PASSWORD_NOT_VALID = 'PASSWORD_NOT_VALID';
export const WRONG_CREDENTIAL = 'WRONG_CREDENTIAL';
